### PR TITLE
:bug: audioContext won't be created without user gesture

### PR DESCRIPTION
**Pull request by snowymo**
so I associated it with the button 'speak' for the current hack. There should be a better way to initiate it.

### CODE REVIEW

**Comment by snowymo** [comment]
@IanTyf try this branch and let me know if audio is working or not.

**Comment by IanTyf** [comment]
Audio is working with this branch! The only issue is that the mute button does not seem to work. I can still hear myself after pressing mute, and it seems that my voice would get even louder (as if there are two "me" talking simultaneously from the same source)

**Comment by snowymo** [comment]
> Audio is working with this branch! The only issue is that the mute button does not seem to work. I can still hear myself after pressing mute, and it seems that my voice would get even louder (as if there are two "me" talking simultaneously from the same source)

That is ... weird. Let me take a look and invite you to test it later.

**Comment by snowymo** [comment]
Solved in another branch.

Thinking what should be the user gesture for VR headset?

**Pull request closed without merging**
