### PR TITLE
Text format Demo

### PR DESCRIPTION
**Pull request by rachelombok**
Text format Demo!

https://user-images.githubusercontent.com/43306992/140985559-ac7dcb27-333f-4118-84fa-1bac7db6a069.mov

### CODE REVIEW

**Comment by snowymo** [comment]
@rachelombok 
image
Plz pull the latest version and take a look and see if the branch behaves as you want.

**Comment by snowymo** [comment]
@rachelombok this commit https://github.com/futurerealitylab/immersive-presentation/pull/39/commits/96f62af6da885661735ee7afb87d7bda7503df2a has a lot of files involved. What happened?

**Comment by rachelombok** [comment]
I was just rebasing and updating my branch to the most up to date version of the main one. Should I roll it back to how it was previously? I thought it should be up to date with how the repo is currently.

**Comment by snowymo** [comment]
> I was just rebasing and updating my branch to the most up to date version of the main one. Should I roll it back to how it was previously? I thought it should be up to date with how the repo is currently.

I've merged it yesterday, see commit 19d4905. So I am not sure why yours has so many changes?

**Comment by rachelombok** [comment]
The current version on my branch was the most up-to-date version of my demo.

**Comment by snowymo** [comment]
> The current version on my branch was the most up-to-date version of my demo.

@rachelombok it has too many changes that are not related to your demo. 
image
Can you confirm?

**Comment by rachelombok** [comment]
okay I see what you mean, I rebased with the main branch as I thought it was the one most up to date, should I rollback my changes from before this commit?

**Review by snowymo — APPROVED** [review]

**Pull request merged**
