### PR TITLE
:tada: add init event that other users will send welcome package to 

### PR DESCRIPTION
**Pull request by snowymo**
the newly joined user, including demoButtons and objects info for now; Welcome pkg will be more than copy for now.

### CODE REVIEW

**Comment by snowymo** [comment]
However, audioContext won't be created until user gesture, that means if other ppl is speaking before newly user joined, new user won't be able to process this though receiving the information.

We may need to hold the info somewhere and process it once the local user has a user gesture.

For example, we maintain the record of speak or not info for each remote users. And we have to update that if new changes come.

**Comment by snowymo** [comment]
@IanTyf try audio thing here, in this branch.

**Comment by IanTyf** [comment]
@snowymo Audio works great in this branch for me!

**Comment by snowymo** [comment]
> @snowymo Audio works great in this branch for me!

Nice. Problem solved. Also, I have questions for your PR about **hit**. Please take a look when you have time.

**Pull request merged**
